version: "3.9"

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    container_name: hashtag-client

    ports:
      - "5173:5173"

    depends_on:
      - server

    volumes:
      - ./client:/app
      - /app/node_modules
    
    env_file:
      - ./client/.env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile

    container_name: hashtag-server

    ports:
      - "9987:9987"

    volumes:
      - ./server:/app
      - /app/node_modules

    env_file:
      - ./server/.env